"""empty message

Revision ID: 01cec1108751
Revises: 733b9c5ca525
Create Date: 2021-04-21 20:46:12.368189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cec1108751'
down_revision = '733b9c5ca525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_id_servicio_registrados_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'id_servicio_registrados')
    op.drop_column('user', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('id_servicio_registrados', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('document_id_servicio_registrados_fkey', 'document', 'servicio_registrados', ['id_servicio_registrados'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
