"""empty message

Revision ID: 3f65e1548772
Revises: e00a34a80235
Create Date: 2021-04-22 21:12:05.566944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f65e1548772'
down_revision = 'e00a34a80235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('id_servicio_registrados', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'document', 'servicio_registrados', ['id_servicio_registrados'], ['id'], ondelete='CASCADE')
    op.add_column('servicio_registrados', sa.Column('portafolioFoto', sa.String(length=100), nullable=True))
    op.drop_column('servicio_registrados', 'file')
    op.add_column('user', sa.Column('photo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    op.add_column('servicio_registrados', sa.Column('file', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('servicio_registrados', 'portafolioFoto')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'id_servicio_registrados')
    # ### end Alembic commands ###
