"""empty message

Revision ID: 50e3c88877d0
Revises: b7f3447b69b6
Create Date: 2021-03-27 19:30:34.725896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e3c88877d0'
down_revision = 'b7f3447b69b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_servicios_prestados', sa.Integer(), nullable=False),
    sa.Column('id_servicio_registrados', sa.Integer(), nullable=False),
    sa.Column('text_comment', sa.String(length=250), nullable=True),
    sa.Column('evaluacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio_registrados'], ['servicio_registrados.id'], ),
    sa.ForeignKeyConstraint(['id_servicios_prestados'], ['servicios_prestados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('servicios_prestados', 'text_comment')
    op.drop_column('servicios_prestados', 'evaluacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicios_prestados', sa.Column('evaluacion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('servicios_prestados', sa.Column('text_comment', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_table('comentarios')
    # ### end Alembic commands ###
