"""empty message

Revision ID: 6a6b55f539b7
Revises: 0ad3e4393d00
Create Date: 2021-03-30 22:31:46.700880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6b55f539b7'
down_revision = '0ad3e4393d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('user', 'userPass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userPass', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
