"""empty message

Revision ID: 7fe8221a7160
Revises: 628bdc1ffc58
Create Date: 2021-04-23 23:26:44.458072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe8221a7160'
down_revision = '628bdc1ffc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicios_prestados', sa.Column('name_servicio', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicios_prestados', 'name_servicio')
    # ### end Alembic commands ###
