"""empty message

Revision ID: a1bd0092c57d
Revises: f75ac9800389
Create Date: 2021-04-20 15:34:13.122447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bd0092c57d'
down_revision = 'f75ac9800389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio_registrados', sa.Column('portafolioFoto', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio_registrados', 'portafolioFoto')
    # ### end Alembic commands ###
