"""empty message

Revision ID: e00a34a80235
Revises: ea0ac39b4f87
Create Date: 2021-04-22 19:54:48.440818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00a34a80235'
down_revision = 'ea0ac39b4f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio_registrados', sa.Column('file', sa.String(length=100), nullable=True))
    op.drop_column('servicio_registrados', 'portafolioFoto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio_registrados', sa.Column('portafolioFoto', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('servicio_registrados', 'file')
    # ### end Alembic commands ###
