"""empty message

Revision ID: f75ac9800389
Revises: b0bc37ba9b6e
Create Date: 2021-04-20 15:10:57.503593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75ac9800389'
down_revision = 'b0bc37ba9b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_id_user_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'id_user')
    op.drop_column('document', 'photo')
    op.add_column('user', sa.Column('photo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    op.add_column('document', sa.Column('photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('document_id_user_fkey', 'document', 'user', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
